[theme]
base="dark"  # Options: "light" or "dark"
primaryColor="#FF746C"  # Change to any color (e.g., Spotify green)
backgroundColor="#121212"  # Dark background
secondaryBackgroundColor="#282828"  # Sidebar color
textColor="#ffffff"  # White text
